# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 00:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usgs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('party', models.TextField()),
                ('state', models.TextField()),
                ('active', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potus', usgs.models.CharacterIdField(null=True)),
                ('vpotus', usgs.models.CharacterIdField(null=True)),
                ('speaker', usgs.models.CharacterIdField(null=True)),
                ('majorityleader', usgs.models.CharacterIdField(null=True)),
                ('majoritywhip', usgs.models.CharacterIdField(null=True)),
                ('minoirtyleader', usgs.models.CharacterIdField(null=True)),
                ('minoritywhip', usgs.models.CharacterIdField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nays', models.ManyToManyField(related_name='nay_votes', to='usgs.Character')),
                ('pres', models.ManyToManyField(related_name='pres_votes', to='usgs.Character')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='usgs.Bill')),
                ('yeas', models.ManyToManyField(related_name='yea_votes', to='usgs.Character')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='cosponsors',
            field=models.ManyToManyField(related_name='cosponsored_bills', to='usgs.Character'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_bills', to='usgs.Character'),
        ),
    ]
