# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name': 'Bill Summary',
                'verbose_name_plural': 'Bill Summaries',
            },
        ),
        migrations.CreateModel(
            name='BillVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('closed', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('modified', models.DateTimeField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='usgs.Bill')),
            ],
            options={
                'verbose_name': 'Bill Version',
                'verbose_name_plural': 'Bill Versions',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField()),
                ('activated', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=2)),
                ('residence', models.CharField(max_length=80)),
                ('party', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('avatar', models.TextField(blank=True, default=b'')),
                ('bio', models.TextField(blank=True, default=b'')),
                ('title', models.CharField(blank=True, default=b'', max_length=80)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majorityleader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usgs.Character')),
                ('majoritywhip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usgs.Character')),
                ('minoirtyleader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usgs.Character')),
                ('minoritywhip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usgs.Character')),
                ('potus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usgs.Character')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usgs.Character')),
                ('vpotus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usgs.Character')),
            ],
        ),
        migrations.CreateModel(
            name='LegislativeBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='usgs.LegislativeBody')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='usgs.LegislativeBody')),
                ('nays', models.ManyToManyField(blank=True, related_name='nay_votes', to='usgs.Character')),
                ('pres', models.ManyToManyField(blank=True, related_name='pres_votes', to='usgs.Character')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='usgs.BillVersion')),
                ('yeas', models.ManyToManyField(blank=True, related_name='yea_votes', to='usgs.Character')),
            ],
        ),
        migrations.AddField(
            model_name='debate',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='usgs.LegislativeBody'),
        ),
        migrations.AddField(
            model_name='debate',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='usgs.BillVersion'),
        ),
        migrations.AddField(
            model_name='billversion',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='usgs.LegislativeBody'),
        ),
        migrations.AddField(
            model_name='bill',
            name='cosponsors',
            field=models.ManyToManyField(blank=True, related_name='cosponsored_bills', to='usgs.Character'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_bills', to='usgs.Character'),
        ),
    ]
