# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-28 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionday',
            old_name='closed',
            new_name='revealed',
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='campaignday',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usgs.ElectionCharacter'),
        ),
    ]
