# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 03:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='modified',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='election',
            name='started',
            field=models.BooleanField(default=True),
        ),
    ]
