# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-08 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, default=b'', max_length=80)),
                ('starttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endttime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='majorityleader',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='majoritywhip',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='minoirtyleader',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='minoritywhip',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='potus',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='vpotus',
        ),
        migrations.RemoveField(
            model_name='character',
            name='title',
        ),
        migrations.DeleteModel(
            name='Leadership',
        ),
        migrations.AddField(
            model_name='holding',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='usgs.Character'),
        ),
    ]
