# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usgs', '0002_auto_20161028_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=80)),
                ('tweet', models.CharField(max_length=200)),
                ('hashtags', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('downs', models.ManyToManyField(blank=True, related_name='_tweet_downs_+', to=settings.AUTH_USER_MODEL)),
                ('ups', models.ManyToManyField(blank=True, related_name='_tweet_ups_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
