# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-09 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0002_auto_20161008_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='endttime',
            new_name='endtime',
        ),
        migrations.AddField(
            model_name='holding',
            name='partytitle',
            field=models.CharField(blank=True, default=b'', max_length=80),
        ),
    ]
