# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0003_auto_20161009_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_type', models.CharField(max_length=80)),
                ('seconded', models.BooleanField(default=False)),
                ('amendment', models.TextField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='debate',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='motion',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='usgs.Debate'),
        ),
        migrations.AddField(
            model_name='motion',
            name='nays',
            field=models.ManyToManyField(blank=True, related_name='_motion_nays_+', to='usgs.Character'),
        ),
        migrations.AddField(
            model_name='motion',
            name='pres',
            field=models.ManyToManyField(blank=True, related_name='_motion_pres_+', to='usgs.Character'),
        ),
        migrations.AddField(
            model_name='motion',
            name='yeas',
            field=models.ManyToManyField(blank=True, related_name='_motion_yeas_+', to='usgs.Character'),
        ),
    ]
