# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0003_auto_20161024_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
    ]
