# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0004_election_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignday',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
