# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0004_auto_20161011_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='usgs.Character')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='usgs.Debate')),
            ],
        ),
        migrations.CreateModel(
            name='DebateMotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_type', models.CharField(max_length=80)),
                ('seconded', models.BooleanField(default=False)),
                ('amendment', models.TextField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usgs.Character')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='usgs.Debate')),
                ('nays', models.ManyToManyField(blank=True, related_name='_debatemotion_nays_+', to='usgs.Character')),
                ('pres', models.ManyToManyField(blank=True, related_name='_debatemotion_pres_+', to='usgs.Character')),
                ('yeas', models.ManyToManyField(blank=True, related_name='_debatemotion_yeas_+', to='usgs.Character')),
            ],
        ),
        migrations.RemoveField(
            model_name='motion',
            name='debate',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='nays',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='pres',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='yeas',
        ),
        migrations.DeleteModel(
            name='Motion',
        ),
    ]
