# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0005_auto_20161013_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatecomment',
            name='timestamp',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debatemotion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='debatemotion',
            name='seconded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usgs.Character'),
        ),
    ]
