# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0006_auto_20161013_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatemotion',
            name='seconded',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usgs.Character'),
        ),
    ]
