# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0006_auto_20161024_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='raised',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usgs.Transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='usgs.Warchest'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='usgs.Warchest'),
        ),
    ]
