# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0007_auto_20161024_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debatecomment',
            options={'verbose_name': 'Bill Comment', 'verbose_name_plural': 'Bill Comments'},
        ),
        migrations.AlterModelOptions(
            name='debatemotion',
            options={'verbose_name': 'Bill Motion', 'verbose_name_plural': 'Bill Motions'},
        ),
        migrations.RenameField(
            model_name='fundraiser',
            old_name='raised',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(),
        ),
    ]
