# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usgs', '0008_auto_20161013_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
