let STATES = {
  'Alaska': "AK",
  'Alabama': "AL",
  'Arkansas': "AR",
  'Arizona': "AZ",
  'California': "CA",
  'Connecticut': "CT",
  'Colorado': "CO",
  'Delaware': "DE",
  'Florida': "FL",
  'Georgia': "GA",
  'Hawaii': "HI",
  'Idaho': "ID",
  'Illinois': "IL",
  'Indiana': "IN",
  'Iowa': "IA",
  'Kansas': "KS",
  'Kentucky': "KY",
  'Louisiana': "LA",
  'Maryland': "MD",
  'Maine': "ME",
  'Massachusetts': "MA",
  'Minnesota': "MN",
  'Michigan': "MI",
  'Mississippi': "MS",
  'Missouri': "MO",
  'Montana': "MT",
  'North Carolina': "NC",
  'Nebraska': "NE",
  'Nevada': "NV",
  'New Hampshire': "NH",
  'New Jersey': "NJ",
  'New York': "NY",
  'North Dakota': "ND",
  'New Mexico': "NM",
  'Ohio': "OH",
  'Oklahoma': "OK",
  'Oregon': "OR",
  'Pennsylvania': "PA",
  'Rhode Island': "RI",
  'South Carolina': "SC",
  'South Dakota': "SD",
  'Tennessee': "TN",
  'Texas': "TX",
  'Utah': "UT",
  'Wisconsin': "WI",
  'Virginia': "VA",
  'Vermont': "VT",
  'Washington': "WA",
  'West Virginia': "WV",
  'Wyoming': "WY",
};

let FROM_STATES = {};

for(let key in STATES){
  FROM_STATES[STATES[key]] = key;
}

export {
  STATES,
  FROM_STATES,
};
